### ISSUE TITLE
Unable to install this library.

### ISSUE THREAD

**Issue by darshantak** [yakupadakli/python-unsplash#10]
After running pip install python-unsplash i am having this error.
AttributeError: 'ParsedRequirement' object has no attribute 'req'

**Comment by zephyo** [comment]
Same

**Comment by Lissanro** [comment]
I'm having this issue too. I also tried installing directly from git but error is the same. Full text of error message:
```
% sudo pip install git+https://github.com/yakupadakli/python-unsplash.git
Collecting git+https://github.com/yakupadakli/python-unsplash.git
  Cloning https://github.com/yakupadakli/python-unsplash.git to /tmp/pip-req-build-4hw2bfpx
  Running command git clone -q https://github.com/yakupadakli/python-unsplash.git /tmp/pip-req-build-4hw2bfpx
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-4hw2bfpx/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-4hw2bfpx/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-9sszzwdk
         cwd: /tmp/pip-req-build-4hw2bfpx/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-4hw2bfpx/setup.py", line 14, in <module>
        requirements = [str(req.req) for req in install_requirements]
      File "/tmp/pip-req-build-4hw2bfpx/setup.py", line 14, in <listcomp>
        requirements = [str(req.req) for req in install_requirements]
    AttributeError: 'ParsedRequirement' object has no attribute 'req'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by Lissanro** [comment]
There is already PR by aayars that fixes this issue. I was able to successfully install it like this:
`sudo pip install git+https://github.com/aayars/python-unsplash.git@setup`

**Comment by darshantak** [comment]
You can install this library by editing the setup.py file.
`import pathlib

import pkg_resources
import setuptools

with pathlib.Path('requirements.txt').open() as requirements_txt:
    install_requires = [
        str(requirement)
        for requirement
        in pkg_resources.parse_requirements(requirements_txt)
    ]

setuptools.setup(
    install_requires=install_requires,
)`

**Comment by yakupadakli** [comment]
Problem solved.
